name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        uses: actions/setup-node@v1
        with: 
          node-version: "18.x"
      - run: npm ci
      - run: npm run format:check
      - run: npm run build
      - run: npm run lint
      # - run: npm test